version: '3.7'

services:
  store:
    build: ./store_service
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./store_service/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  order:
    build: ./order_service
    command: ./manage.py runserver 0.0.0.0:8001
    volumes:
      - ./order_service/:/usr/src/app/
    ports:
      - 8001:8001
    env_file:
      - ./.env.dev
  warehouse:
    build: ./warehouse_service
    command: ./manage.py runserver 0.0.0.0:8002
    volumes:
      - ./warehouse_service/:/usr/src/app/
    ports:
      - 8002:8002
    env_file:
      - ./.env.dev
  warranty:
    build: ./warranty_service
    command: ./manage.py runserver 0.0.0.0:8003
    volumes:
      - ./warranty_service/:/usr/src/app/
    ports:
      - 8003:8003
    env_file:
      - ./.env.dev
