# Generated by Django 3.1.2 on 2020-11-01 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PAID', max_length=255)),
                ('item_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
