name: Build project
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Lint with flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Deploy Order to Heroku
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: "e7a42e44-ebad-4a40-b86d-84f4a75b0ef3"
          heroku_app_name: "shmarov-rsoi-lab2-order"
          heroku_email: "bambookchos@gmail.com"
          appdir: order_service
      - name: Deploy Store to Heroku
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: "e7a42e44-ebad-4a40-b86d-84f4a75b0ef3"
          heroku_app_name: "shmarov-rsoi-lab2-store"
          heroku_email: "bambookchos@gmail.com"
          appdir: store_service
      - name: Deploy Warehouse to Heroku
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: "e7a42e44-ebad-4a40-b86d-84f4a75b0ef3"
          heroku_app_name: "shmarov-rsoi-lab2-warehouse"
          heroku_email: "bambookchos@gmail.com"
          appdir: warehouse_service
      - name: Deploy Warranty to Heroku
        uses: AkhileshNS/heroku-deploy@v3.4.6
        with:
          heroku_api_key: "e7a42e44-ebad-4a40-b86d-84f4a75b0ef3"
          heroku_app_name: "shmarov-rsoi-lab2-warranty"
          heroku_email: "bambookchos@gmail.com"
          appdir: warranty_service
      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/postman-collection.json
          environment: postman/postman-heroku-environment.json
          delayRequest: 50
          reporters: cli
